### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by benjamingr**

### CODE REVIEW

**Comment by conorhastings** [comment]
thank you @benjamingr :tada:

**Comment by benjamingr** [comment]
If you're here already - does this package support overlay? (backdrop)

**Comment by conorhastings** [comment]
not currently no :disappointed:

**Comment by benjamingr** [comment]
Ok, what about responsive screens?

**Comment by conorhastings** [comment]
not sure, I believe it should, the styles are all overridable as well.

**Pull request merged**
